"""Provider-neutral mission operator primitives."""

from astro_operator.behavior import (
    BehaviorDisposition,
    ReasonerBehaviorCorpus,
    ReasonerBehaviorReplay,
    ReasonerBehaviorScore,
    load_reasoner_behavior_corpus,
    load_reasoner_behavior_replay,
    score_reasoner_behavior_corpus,
)
from astro_operator.engine import run_operator
from astro_operator.errors import (
    ReasonerCancelledError,
    ReasonerConfigurationError,
    ReasonerError,
    ReasonerInvalidResponseError,
    ReasonerUnavailableError,
)
from astro_operator.evaluation import (
    AdversarialCorpusScore,
    AdversarialDecisionCorpus,
    DecisionDisposition,
    load_adversarial_corpus,
    score_adversarial_corpus,
)
from astro_operator.models import (
    ActionApproval,
    AuthorityGrant,
    AuthorityLevel,
    CandidateObservation,
    CandidateProposal,
    CommandRequest,
    CommandResult,
    DesignVariable,
    EpistemicKind,
    EvidenceReference,
    MetricGoal,
    MissionObjective,
    OperatorAction,
    OperatorActionKind,
    OperatorRun,
    OperatorRunStatus,
    ReasonerDecision,
    ReasonerInvocation,
)
from astro_operator.openrouter import OpenRouterReasoner
from astro_operator.policy import validate_action_against_state, validate_operator_state
from astro_operator.reasoner import (
    BoundDecisionReasoner,
    ConditionalReplayReasoner,
    InvocationRecordingReasoner,
    ScriptedReasoner,
    validate_reasoner_decision,
)
from astro_operator.recording import (
    ReasonerAttribution,
    ReasonerBehaviorRecording,
    RecordedReasonerBehaviorScore,
    load_reasoner_behavior_recording,
    record_reasoner_behavior_replay,
    score_recorded_reasoner_behavior_corpus,
    write_reasoner_behavior_recording,
)

__all__ = [
    "ActionApproval",
    "AdversarialCorpusScore",
    "AdversarialDecisionCorpus",
    "AuthorityGrant",
    "AuthorityLevel",
    "BehaviorDisposition",
    "BoundDecisionReasoner",
    "CandidateObservation",
    "CandidateProposal",
    "CommandRequest",
    "CommandResult",
    "ConditionalReplayReasoner",
    "DesignVariable",
    "DecisionDisposition",
    "EpistemicKind",
    "EvidenceReference",
    "InvocationRecordingReasoner",
    "MetricGoal",
    "MissionObjective",
    "OperatorAction",
    "OperatorActionKind",
    "OperatorRun",
    "OperatorRunStatus",
    "OpenRouterReasoner",
    "ReasonerDecision",
    "ReasonerBehaviorCorpus",
    "ReasonerBehaviorReplay",
    "ReasonerBehaviorScore",
    "ReasonerBehaviorRecording",
    "ReasonerAttribution",
    "ReasonerCancelledError",
    "ReasonerConfigurationError",
    "ReasonerError",
    "ReasonerInvalidResponseError",
    "ReasonerInvocation",
    "RecordedReasonerBehaviorScore",
    "ReasonerUnavailableError",
    "ScriptedReasoner",
    "run_operator",
    "load_adversarial_corpus",
    "load_reasoner_behavior_corpus",
    "load_reasoner_behavior_replay",
    "load_reasoner_behavior_recording",
    "record_reasoner_behavior_replay",
    "score_adversarial_corpus",
    "score_reasoner_behavior_corpus",
    "score_recorded_reasoner_behavior_corpus",
    "validate_action_against_state",
    "validate_operator_state",
    "validate_reasoner_decision",
    "write_reasoner_behavior_recording",
]
